info:
  name: teambuiltingexperience
  description: Team Builting Experience Microservice, to enhance the team builting experience!

server:
  port: ${PORT:8082}
---

# Queue configuration
messaging:
  amqp:
    team:
      exchange:
        name: TEAMBUILTING.E.TEAM
        durable: true
        autodelete: false
      queue:
        name: TEAMBUILTING.Q.EXPERIENCE.TEAM
        binding: team.deleted
        durable: true
        autodelete: false
    player:
      exchange:
        name: TEAMBUILTING.E.PLAYER
        durable: true
        autodelete: false
      queue:
        name: TEAMBUILTING.Q.EXPERIENCE.PLAYER
        binding: player.deleted
        durable: true
        autodelete: false

---

spring:
  profiles: production
  data.mongodb:
    database: teambuiltingexperience # Database name.
    host: ${MONGODB_HOST} # Mongo server host.
    port: ${MONGODB_PORT} # Mongo server port.
    username: ${MONGODB_USERNAME} # Login user of the mongo server.
    password: ${MONGODB_PASSWORD} # Login password of the mongo server.
    repositories.enabled: true # Enable Mongo repositories.
  rabbitmq:
      username: ${RABBITMQ_USERNAME}
      virtual-host: ${RABBITMQ_VIRTUAL_HOST}
      password: ${RABBITMQ_PASSWORD}
      host: ${RABBITMQ_HOST}
    
--- 
  
spring:
  profiles: dev
  data.mongodb:
    database: teambuiltingexperience # Database name.
    host: localhost # Mongo server host.
    port: 27017 # Mongo server port.
    repositories.enabled: true # Enable Mongo repositories.
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672



endpoints:
  enabled: true # Enable endpoints.
  actuator.enabled: true # Enable the endpoint.

---